def rename (df):
    df.rename(columns={
                    "portfolio_name": "Portfolio",
                    "portfolio_id":"ID Carteira",
                    "date":"Data",
                    "mask_name":"Máscara",
                    "mask_id":"Máscara ID",
                    "id":"ID",
                    "book_name":"Book",
                    "book_id":"Book ID",
                    "liquidity_redemption_term":"Liq. Resgate",
                    "calendar_days_to_redemption":"Dias p/ Resgate",
                    "absolute_nav":"PL Absoluto",
                    "portfolio_nav":"PL do Portfólio",
                    "value_1":"1(%)",
                    "financial_value_1":"1",
                    "value_2":"2(%)",
                    "financial_value_2":"2",
                    "value_3":"3(%)",
                    "financial_value_3":"3",
                    "value_4":"4(%)",
                    "financial_value_4":"4",
                    "value_6":"6(%)",
                    "financial_value_6":"6",
                    "value_5":"5(%)",
                    "financial_value_5":"5",
                    "value_10":"10(%)",
                    "financial_value_10":"10",
                    "value_21":"21(%)",
                    "financial_value_21":"21",
                    "value_42":"42(%)",
                    "financial_value_42":"42",
                    "value_32":"32(%)",
                    "financial_value_32":"32",  
                    "value_63":"63(%)",
                    "financial_value_63":"63",                    
                    "value_126":"126(%)",
                    "financial_value_126":"126",
                    "redemption_type":"Tipo",
                    "configuration_id":"ID Configuração",
                    "is_probability":"É Probabilidade",
                    "instrument_symbol": "Ticker",
                    "instrument_id": "Ticker ID",
                    "instrument_type": "Tipo do Ticker",
                    "instrument_name": "Nome",
                    "account_name":"Conta",
                    "liquidity_premium":"Prêmio de Liquidez",
                    "price":"Preço",
                    "transaction_value":"Valor da Transação",
                    "transaction_name":"Nome da Transação",
                    "calendar_days_to_settle":"Dias p/ liquidar",
                    "calculation_response":"Resposta do Cálculo",
                    "quantity_adjusted_average":"ADTV Qtd.",
                    "financial_adjusted_average":"ADTV Fin.",
                    "adjusted_average":"zzz_repetidos",
                    "contract_id":"Contrato ID",
                    "account_id":"Conta ID",
                    "is_collateral":"É Garantia",
                    "origin_accounting_transaction_id": "Conta de Origem ID",
                    "exposure_value":"Valor de Exposição",
                    "percentual_exposure":"Exposição %",
                    "absolute_exposure":"Exposição Absoluta",
                    "percentual_absolute_exposure": "Exposição Absoluta %",
                    "quantity":"Quantidade",

                }, inplace=True)
    
    return df


