mapa_renomeacao_ativos = {
    "instrument_symbol": "Ticker",
    "instrument_id": "Ticker ID",
    "instrument_type": "Tipo do Ticker",
    "instrument_name": "Nome",
    "position_overview_id": "ID Posição",
    "book_name": "Book",
    "available_quantity": "Quantidade Disponível",
    "borrowed_quantity": "Quantidade Tomada",
    "collateral_quantity": "Quantidade em Garantia",
    "currency_exchange_rate": "Câmbio",
    "price": "Preço",
    "exposure_value": "Valor de Exposição",
    "pct_asset_value": "Exposição %",
    "pct_net_asset_value": "VL Financeiro %",
    "asset_value": "Vl. Financeiro",
    "last_asset_value": "Vl. Financeiro D-1",
    "duration": "Duração",
    "rate": "Taxa",
    "accrued_interest": "Juros Acumulados",
    "price_date": "Dt. Início",
    "last_price": "Preço D-1",
    "last_exposure_value": "Valor de Exposição D-1",
    "attribution.portfolio_beta.financial_value": "PnL Beta",
    "attribution_portfolio_beta_percentage": "Repetido_attribution_portfolio_beta_percentage",
    "attribution_portfolio_beta_financial": "Repetido_attribution_portfolio_beta_financial",
    "attribution.portfolio_beta.percentage_value": "PnL % Beta",
    "attribution.total.financial_value": "PnL Total",
    "attribution.total.percentage_value": "PnL % Total",
    "attribution_total_financial": "Repetido_attribution_total_financial",
    "attribution_total_percentage": "Repetido_attribution_total_percentage",
    "attribution.currency.financial_value": "PnL Moeda",
    "attribution.currency.percentage_value": "PnL % Moeda",
    "attribution_currency_financial": "Repetido_attribution_currency_financial",
    "attribution_currency_percentage": "Repetido_attribution_currency_percentage",
    "quantity": "Quantidade",
    "unsettled_quantity": "Quantidade não liquidada",
    "delta_price": "Preço %",
    "price_information_type_id": "Repetido_price_information_type_id",
    "overview_date": "Repetido_overview_date",
    "original_currency_id": "ID da moeda original",
    "lent_quantity": "Quantidade Doada",
    "lent_position_percentage": "Posição Doada %",
    "exposure_unit_value": "Preço Exposição",
    "currency_exchange_rate_date": "Câmbio (Data)",
    "currency_exchange_rate_instrument_id": "Câmbio (ID)",
    "book_id": "Book ID",
    "average_term": "Prazo Médio",
    "attribution.total_hedged.percentage_value": "Repetido_attribution.total_hedged.percentage_value",
    "attribution.total_hedged.financial_value": "Repetido_attribution.total_hedged.financial_value",
    "corp_actions_adj_factor": "Fator de Ajuste por Eventos Societários",
    "attribution.corp_actions.financial_value": "PnL Eventos Societários",
    "attribution.corp_actions.percentage_value": "PnL % Eventos Societários",
    "attribution.par_price.financial_value": "PnL Preço de Paridade",
    "attribution.par_price.percentage_value": "PnL % Preço de Paridade",
    "lending_unsettled_quantity": "Quantidade a Liquidar (Empréstimo)",
    "total_investment": "Investimento Total",
    "account_id": "Repetido_account_id",
    "account_name": "Repetido_account_name",
    "accrued_interest_admin_id": "Repetido_accrued_interest_admin_id",
    "accrued_interest_contract_id": "Repetido_accrued_interest_contract_id",
    "accrued_interest_date": "Repetido_accrued_interest_date",
    "accrued_interest_portfolio_id": "Repetido_accrued_interest_portfolio_id",
    "acquisition_rate": "Repetido_acquisition_rate",
    "adtv": "Repetido_adtv",
    "sector_name": "Setor",
    "sector_id": "Setor ID",
    "issuer_name": "Emissor",
    "issuer_id": "Emissor ID"
}


                # Renomeações para CPR
mapa_renomeacao_cpr = {
    "name": "Nome",
    "category_name": "Categoria",
    "portfolio": "Carteira",
    "date": "Data",
    "value": "Valor",
    "settlement_date": "Data de Liquidação",
    "book_name": "Book",
    "account_name": "Conta",
    "attribution.portfolio_beta.financial_value": "PnL Beta",
    "attribution.portfolio_beta.percentage_value": "PnL % Beta",
    "pnl_total": "PnL Total",
    "pnl_percentage_total": "PnL % Total",
    "pnl_currency": "PnL Moeda",
    "pnl_currency_percentage": "PnL % Moeda",
    "account_id": "Conta ID",
    "attribution.total.financial_value": "PnL Total",
    "attribution.total.percentage_value": "PnL % Total",
    "attribution.total_hedged.financial_value": "Repetido_attribution.total_hedged.financial_value",
    "attribution.total_hedged.percentage_value": "Repetido_attribution.total_hedged.percentage_value",
    "attribution_total_financial": "Repetido_attribution_total_financial",
    "attribution_total_percentage": "Repetido_attribution_total_percentage",
    "book_id": "Book ID",
    "category_id": "Categoria ID",
    "currency_exchange_rate": "Câmbio",
    "currency_exchange_rate_date": "Câmbio (Data)",
    "currency_exchange_rate_instrument_id": "Câmbio (ID)",
    "financial_value": "Valor",
    "is_foreign_currency": "Moeda Estrangeira",
    "is_totally_settled": "Totalmente Liquidada",
    "origin_accounting_transaction_id": "ID Transação Contábil de Origem",
    "origin_instrument_id": "Carteira de Origem ID",
    "original_currency_id": "Moeda Original ID",
    "original_financial_value": "Valor Original",
    "original_settled_value": "Repetido_original_settled_value",
    "pct_net_asset_value": "Exposição %",
    "pnl_book_id": "PNL Book ID",
    "position_overview_id": "ID Posição Carteira",
    "settled_value": "Liq. até a data",
    "source_content_type_id": "ID Tipo de Conteúdo de Origem",
    "source_object_id": "ID Objeto de Origem",
    "origin_contract_id": "ID do Contrato de Origem",
    "profitability_start_date": "%Dt Início",
    "profitability_in_day": "%Dia",
    "profitability_in_month": "%Mês",
    "profitability_in_semester": "%Semestre",
    "profitability_in_6_months": "%6 Meses",
    "profitability_in_year": "%Ano",
    "profitability_in_12_months": "%12 Meses",
    "profitability_in_18_months": "%18 Meses",
    "profitability_in_24_months": "%24 Meses",
    "profitability_in_30_months": "%30 Meses",
    "profitability_in_36_months": "%36 Meses",
    "profitability_in_48_months": "%48 Meses",
    "profitability_in_60_months": "%60 Meses",
    "net_asset_value": "PL",
    "portfolio_id": "ID Carteira",
    "overview_type": "Tipo de Overview",
    "instrument_positions": "Ativos",
    "last_shares": "Qtd. Cotas D-1",
    "is_opening": "Carteira de Abertura",
    "id": "ID Overview",
    "navps": "Cota Líquida",
    "gross_navps": "Cota bruta",
    "shares": "Qtd. Cotas",
    "fixed_shares": "Qtd. Cotas Fixas",
    "portfolio_average_duration": "Duração Média Carteira",
    "created_on": "Data de Criação",
    "benchmark_profitability.profitability_in_day": "Bench %Dia",
    "benchmark_profitability.profitability_in_month": "Bench %Mês",
    "benchmark_profitability.profitability_in_year": "Bench %Ano",
    "benchmark_profitability.profitability_in_12_months": "Bench %12 Meses",
    "benchmark_profitability.profitability_start_date": "Bench %Dt Início",
    "benchmark_profitability.profitability_in_semester": "Bench %Semestre",
    "benchmark_profitability.profitability_in_6_months": "Bench %6 Meses",
    "benchmark_profitability.profitability_in_18_months": "Bench %18 Meses",
    "benchmark_profitability.profitability_in_24_months": "Bench %24 Meses",
    "benchmark_profitability.profitability_in_30_months": "Bench %30 Meses",
    "benchmark_profitability.profitability_in_36_months": "Bench %36 Meses",
    "benchmark_profitability.profitability_in_48_months": "Bench %48 Meses",
    "benchmark_profitability.profitability_in_60_months": "Bench %60 Meses",
    "modified_on": "Modificado em",
    "released_on": "Data de Liberação",
    "benchmark_profitability.symbol": "Nome Bench",
    "gross_asset_value": "Valor Bruto",
    "asset_value_for_allocation": "Valor para Alocação",
    "last_net_asset_value": "PL D-1",
    "last_navps": "Cota Líquida D-1",
    "fixed_navps": "Cota Fixa",
    "financial_transaction_positions": "CPR",
    "attribution_portfolio_beta_percentage": "Repetido_attribution_portfolio_beta_percentage",
    "attribution_portfolio_beta_financial": "Repetido_attribution_portfolio_beta_financial",
    "attribution_total_financial": "Repetido_attribution_total_financial2",
    "attribution_total_percentage": "Repetido_attribution_total_percentage2",
    "attribution_currency_financial": "Repetido_attribution_currency_financial",
    "attribution_currency_percentage": "Repetido_attribution_currency_percentage",
    "attribution_maximums.par_price": "PnL Máximo Preço Par",
    "attribution_maximums.portfolio_beta": "PnL Máximo Beta da Carteira",
    "attribution_maximums.total": "PnL Máximo Total",
    "attribution_maximums.total_hedged": "PnL Máximo Total Hedgeado",
    "corp_actions_adjusted_navps": "Cota Líquida Ajustada por Eventos Societários",
    "corp_actions_factor": "Fator de Ajuste por Eventos Societários",
    "equity_exposure": "Exposição em Renda Variável",
    "is_system_generated": "Gerado pelo Sistema",
    "navps_admin_status": "Status Administrativo da Cota Líquida",
    "navps_one_day_return": "Retorno Diário da Cota Líquida",
    "navps_status": "Status da Cota Líquida",
    "net_liabilities_transactions_financial_value": "Valor Financeiro das Transações de Passivo Líquido",
    "overview_status": "Status do Overview",
    "pct_lent_exposure": "Exposição % Doada",
    "portfolio_average_term": "Prazo Médio da Carteira",
    "attribution_maximums.corp_actions": "PnL Máximo Eventos Societários",
    "attribution_maximums.currency": "PnL Máximo  Moeda"
}


def rename(df):
    df.rename(columns={
        "name": "Nome",
        "category_name": "Categoria",
        "portfolio": "Carteira",
        "date": "Data",
        "value": "Valor",
        "settlement_date": "Data de Liquidação",
        "book_name": "Book",
        "account_name": "Conta",
        "attribution.portfolio_beta.financial_value": "PnL Beta",
        "attribution.portfolio_beta.percentage_value": "PnL % Beta",
        "pnl_total": "PnL Total",
        "pnl_percentage_total": "PnL % Total",
        "pnl_currency": "PnL Moeda",
        "pnl_currency_percentage": "PnL % Moeda",
        "account_id": "Conta ID",
        "attribution.total.financial_value": "PnL Total",
        "attribution.total.percentage_value": "PnL % Total",
        "attribution.total_hedged.financial_value": "Repetido_attribution.total_hedged.financial_value",
        "attribution.total_hedged.percentage_value": "Repetido_attribution.total_hedged.percentage_value",
        "attribution_total_financial": "Repetido_attribution_total_financial",
        "attribution_total_percentage": "Repetido_attribution_total_percentage",
        "book_id": "Book ID",
        "category_id": "Categoria ID",
        "currency_exchange_rate": "Câmbio",
        "currency_exchange_rate_date": "Câmbio (Data)",
        "currency_exchange_rate_instrument_id": "Câmbio (ID)",
        "financial_value": "Valor",
        "is_foreign_currency": "Moeda Estrangeira",
        "is_totally_settled": "Totalmente Liquidada",
        "origin_accounting_transaction_id": "ID Transação Contábil de Origem",
        "origin_instrument_id": "Carteira de Origem ID",
        "original_currency_id": "Moeda Original ID",
        "original_financial_value": "Valor Original",
        "original_settled_value": "Repetido_original_settled_value",
        "pct_net_asset_value": "Exposição %",
        "pnl_book_id": "PNL Book ID",
        "position_overview_id": "ID Posição Carteira",
        "settled_value": "Liq. até a data",
        "source_content_type_id": "ID Tipo de Conteúdo de Origem",
        "source_object_id": "ID Objeto de Origem",
        "origin_contract_id": "ID do Contrato de Origem",
        "profitability_start_date": "%Dt Início",
        "profitability_in_day": "%Dia",
        "profitability_in_month": "%Mês",
        "profitability_in_semester": "%Semestre",
        "profitability_in_6_months": "%6 Meses",
        "profitability_in_year": "%Ano",
        "profitability_in_12_months": "%12 Meses",
        "profitability_in_18_months": "%18 Meses",
        "profitability_in_24_months": "%24 Meses",
        "profitability_in_30_months": "%30 Meses",
        "profitability_in_36_months": "%36 Meses",
        "profitability_in_48_months": "%48 Meses",
        "profitability_in_60_months": "%60 Meses",
        "net_asset_value": "PL",
        "portfolio_id": "ID Carteira",
        "overview_type": "Tipo de Overview",
        "instrument_positions": "Ativos",
        "last_shares": "Qtd. Cotas D-1",
        "is_opening": "Carteira de Abertura",
        'id': 'ID Overview',
        "navps": "Cota Líquida",
        "gross_navps": "Cota bruta",
        "shares": "Qtd. Cotas",
        "fixed_shares": "Qtd. Cotas Fixas",
        "portfolio_average_duration": "Duração Média Carteira",
        "created_on": "Data de Criação",
        "benchmark_profitability.profitability_in_day": "Bench %Dia",
        "benchmark_profitability.profitability_in_month": "Bench %Mês",
        "benchmark_profitability.profitability_in_year": "Bench %Ano",
        "benchmark_profitability.profitability_in_12_months": "Bench %12 Meses",
        "benchmark_profitability.profitability_start_date": "Bench %Dt Início",
        "benchmark_profitability.profitability_in_semester": "Bench %Semestre",
        "benchmark_profitability.profitability_in_6_months": "Bench %6 Meses",
        "benchmark_profitability.profitability_in_18_months": "Bench %18 Meses",
        "benchmark_profitability.profitability_in_24_months": "Bench %24 Meses",
        "benchmark_profitability.profitability_in_30_months": "Bench %30 Meses",
        "benchmark_profitability.profitability_in_36_months": "Bench %36 Meses",
        "benchmark_profitability.profitability_in_48_months": "Bench %48 Meses",
        "benchmark_profitability.profitability_in_60_months": "Bench %60 Meses",
        "modified_on": "Modificado em",
        "released_on": "Data de Liberação",
        "benchmark_profitability.symbol": "Nome Bench",
        "gross_asset_value": "Valor Bruto",
        "asset_value_for_allocation": "Valor para Alocação",
        "last_net_asset_value": "PL D-1",
        "last_navps": "Cota Líquida D-1",
        "fixed_navps": "Cota Fixa",
        "financial_transaction_positions": "CPR",
        "attribution_portfolio_beta_percentage": "Repetido_attribution_portfolio_beta_percentage",
        "attribution_portfolio_beta_financial": "Repetido_attribution_portfolio_beta_financial",
        "attribution_currency_financial": "Repetido_attribution_currency_financial",
        "attribution_currency_percentage": "Repetido_attribution_currency_percentage",
        "attribution_maximums.par_price": "PnL Máximo Preço Par",
        "attribution_maximums.portfolio_beta": "PnL Máximo Beta da Carteira",
        "attribution_maximums.total": "PnL Máximo Total",
        "attribution_maximums.total_hedged": "PnL Máximo Total Hedgeado",
        "corp_actions_adjusted_navps": "Cota Líquida Ajustada por Eventos Societários",
        "corp_actions_factor": "Fator de Ajuste por Eventos Societários",
        "equity_exposure": "Exposição em Renda Variável",
        "is_system_generated": "Gerado pelo Sistema",
        "navps_admin_status": "Status Administrativo da Cota Líquida",
        "navps_one_day_return": "Retorno Diário da Cota Líquida",
        "navps_status": "Status da Cota Líquida",
        "net_liabilities_transactions_financial_value": "Valor Financeiro das Transações de Passivo Líquido",
        "overview_status": "Status do Overview",
        "pct_lent_exposure": "Exposição % Doada",
        "portfolio_average_term": "Prazo Médio da Carteira",
        "attribution_maximums.corp_actions": "PnL Máximo Eventos Societários",
        "attribution_maximums.currency": "PnL Máximo Moeda",
        "instrument_symbol": "Ticker",
        "instrument_id": "Ticker ID",
        "instrument_type": "Tipo do Ticker",
        "instrument_name": "Nome",
        "position_overview_id": "ID Posição",
        "book_name": "Book",
        "available_quantity": "Quantidade Disponível",
        "borrowed_quantity": "Quantidade Tomada",
        "collateral_quantity": "Quantidade em Garantia",
        "currency_exchange_rate": "Câmbio",
        "price": "Preço",
        "exposure_value": "Valor de Exposição",
        "pct_asset_value": "Exposição %",
        "asset_value": "Vl. Financeiro",
        "last_asset_value": "Vl. Financeiro D-1",
        "duration": "Duração",
        "rate": "Taxa",
        "accrued_interest": "Juros Acumulados",
        "price_date": "Dt. Início",
        "last_price": "Preço D-1",
        "last_exposure_value": "Valor de Exposição D-1",
        "attribution.par_price.financial_value": "PnL Preço de Paridade",
        "attribution.par_price.percentage_value": "PnL % Preço de Paridade",
        "lending_unsettled_quantity": "Quantidade a Liquidar (Empréstimo)",
        "total_investment": "Investimento Total",
        "account_id": "Repetido_account_id",
        "account_name": "Repetido_account_name",
        "accrued_interest_admin_id": "Repetido_accrued_interest_admin_id",
        "accrued_interest_contract_id": "Repetido_accrued_interest_contract_id",
        "accrued_interest_date": "Repetido_accrued_interest_date",
        "accrued_interest_portfolio_id": "Repetido_accrued_interest_portfolio_id",
        "acquisition_rate": "Repetido_acquisition_rate",
        "adtv": "Repetido_adtv",
        "sector_name": "Setor",
        "sector_id": "Setor ID",
        "issuer_name": "Emissor",
        "issuer_id": "Emissor ID"
    }, inplace=True)
    return df
